# Generated by Django 5.2.1 on 2025-05-22 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Autopart', '0002_tipocliente_remove_producto_precio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='producto',
            name='marca',
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='telefono',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
