# Generated by Django 5.2.1 on 2025-05-30 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Autopart', '0003_remove_producto_categoria_remove_producto_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='Autopart.categoria'),
            preserve_default=False,
        ),
    ]
