# Generated by Django 5.2.1 on 2025-05-30 21:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Autopart', '0004_producto_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='marca',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='Autopart.marca'),
            preserve_default=False,
        ),
    ]
