# Generated by Django 5.2.1 on 2025-05-30 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Autopart', '0005_producto_marca'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos/'),
        ),
    ]
