# Generated by Django 5.2.1 on 2025-05-31 06:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Autopart', '0006_producto_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='alto',
            field=models.DecimalField(decimal_places=2, default=1, help_text='Alto en centímetros', max_digits=6, validators=[django.core.validators.MinValueValidator(0.01)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='ancho',
            field=models.DecimalField(decimal_places=2, default=1, help_text='Ancho en centímetros', max_digits=6, validators=[django.core.validators.MinValueValidator(0.01)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='largo',
            field=models.DecimalField(decimal_places=2, default=1, help_text='Largo en centímetros', max_digits=6, validators=[django.core.validators.MinValueValidator(0.01)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='peso',
            field=models.DecimalField(decimal_places=2, default=1, help_text='Peso en kilogramos', max_digits=6, validators=[django.core.validators.MinValueValidator(0.01)]),
            preserve_default=False,
        ),
    ]
