# Generated by Django 5.2.1 on 2025-06-01 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Autopart', '0007_producto_alto_producto_ancho_producto_largo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='envio',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
    ]
