# Generated by Django 5.2.1 on 2025-06-02 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Autopart', '0008_order_envio'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='iva',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='subtotal',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='total',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='envio',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
