# Generated by Django 5.2.1 on 2025-06-02 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Autopart', '0009_order_iva_order_subtotal_order_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado'), ('rechazado', 'Rechazado'), ('cancelado', 'Cancelado'), ('recibido', 'Recibido'), ('retirado', 'Retirado')], default='pendiente', max_length=20),
        ),
    ]
