# Generated by Django 5.2.1 on 2025-06-03 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Autopart', '0010_order_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarcaAuto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='marcas_auto',
            field=models.ManyToManyField(blank=True, related_name='productos', to='Autopart.marcaauto'),
        ),
    ]
