# Generated by Django 5.2.1 on 2025-06-03 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Autopart', '0011_marcaauto_producto_marcas_auto'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='categorias/'),
        ),
        migrations.AddField(
            model_name='marca',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='marcas/'),
        ),
        migrations.AddField(
            model_name='marcaauto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='marcas_auto/'),
        ),
        migrations.AddField(
            model_name='producto',
            name='descuento_oferta',
            field=models.PositiveIntegerField(blank=True, help_text='Porcentaje de descuento (ej: 15 para 15%)', null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='oferta_activa',
            field=models.BooleanField(default=False, verbose_name='¿Está en oferta?'),
        ),
        migrations.AddField(
            model_name='producto',
            name='precio_oferta_mayorista',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='precio_oferta_minorista',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
